/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full install. It is checked in here so
// TypeScript-aware editors understand the scaffold before dependencies exist.
